### ISSUE TITLE
Add prefer-const rule

### ISSUE THREAD

**Issue by joselanderosmrf** [Marfeel/MarfeelCodingStandards#10]
# Rule to add
prefer-const

[ESLint link reference](https://eslint.org/docs/rules/prefer-const)

# Description (optional)
Raise error when a let variable is never reassigned.

# Example bad code with the rule
```javascript
// bad
let a = 3;

console.log(a);

// `a` is redefined (not reassigned) on each loop step.
for (let a of [1, 2, 3]) {
    console.log(a);
}
```

# Example good code with the rule
```javascript
// good
const a = 3;

console.log(a);

// `a` is redefined (not reassigned) on each loop step.
for (const a of [1, 2, 3]) {
    console.log(a);
}
```

**Comment by dominguezcelada** [comment]
Hi team! Which should be the flow to move this forward?

**Comment by stefanosaittamrf** [comment]
@dominguezcelada propose a PR for this

**Comment by alexmrf** [comment]
Merged!
