### ISSUE TITLE
Add usage into the readme.md

### ISSUE THREAD

**Issue by stefanosaittamrf** [Marfeel/MarfeelCodingStandards#7]
I would like to document a bit more the `README.md` in order to explain how to use, caveats, known issue etc

**Comment by dominguezcelada** [comment]
@stefanosaittamrf which is the approach to move this forward?

**Comment by stefanosaittamrf** [comment]
@dominguezcelada i'm not the owner of this project. You should ask @alexmrf or @marcmrf
